// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            4
// Async Callback (empty):               1
// Total number of exported functions:   7

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    nft_academic
    (
        init => init
        upgrade => upgrade
        enrollInstitution => enroll_institution
        whitelistAddress => whitelist_address
        getEnrolledInstitutions => enrolled_institutions
        getEnrollmentFee => enrollment_fee
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
